export { default as ico } from "./ico.png";
export { default as hamburger } from "./hamburger.png";
export { default as close } from "./close.png";
export { default as landingMobilebg2 } from "./landing_mobile_bg2.jpg";
export { default as landingMobilebg3 } from "./landing_mobile_bg3.jpg";
export { default as landingMobilebg4 } from "./landing_mobile_bg4.jpg";
export { default as landingbg6 } from "./landing_desktop_bg6.jpg";
export { default as landingbg8 } from "./landing_desktop_bg8.jpg";
export { default as landingMobilebg9 } from "./landing_mobile_bg9.jpg";
